name: Block on fixup commits

on: pull_request_target

permissions:
  pull-requests: read

jobs:
  message:
    uses: xt0rted/.github/.github/workflows/fixup-commits.yml@cb2d8c639d7292c04de6e740bf557e7b8f751f7f # main
